services:
  Snoke\SoftDelete\:
    autowire: true
    autoconfigure: true
    resource: '../../'
    exclude:
      - '../../Entity/'
  Snoke\SoftDelete\EventListener\FlushListener:
    arguments:
      $detach: '%snoke_soft_delete.detach%'